In [29]:
'''
Our KNN algorithm
## in general, pick an odd k

'''
# imports go here
import pandas as pd
import numpy as np
import scipy.spatial

In [31]:
'''
Part 1: Setting it all up
'''

# we will need a euclidean_distance_algorithm that takes in
# two numpy arrays, and calculates the 
# euclidean distance between them

def euclidean_distance(np1, np2):
    dist = scipy.spatial.distance.euclidean(np1, np2)
    return dist

euclidean_distance([1,1],[2,2])


1.4142135623730951

In [32]:
'''
Bring in the iris data from the web

iris_data ==
    2D numpy array of the four predictors of iris
        plus the species
'''

iris_data = pd.read_csv('https://raw.githubusercontent.com/sinanuozdemir/sfdat22/master/data/iris.csv')
# iris_data is a dataframe, but let's turn it into
# a 2D numpy array
# Hint: use .values to turn a dataframe into a 2d array

iris_data = iris_data.values

In [33]:
# Question: in terms of machine learning:
#   a. the first four columns are called what?
#   b. the species column is called what?

'''
array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       ... ...
       [6.2, 3.4, 5.4, 2.3, 'Iris-virginica'],
       [5.9, 3.0, 5.1, 1.8, 'Iris-virginica']], dtype=object)
'''

iris_data



array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [34]:
'''
Part 2: Predictions

Before we jump into making a general function,
let's try to predict 

unknown = [ 6.3,  3.1 ,  5.1,  2.4] with 3 neighbors
'''

# define our variables
unknown = [ 6.3,  3.1 ,  5.1,  2.4]
k = 3

In [72]:
# Make a a list "distances" consisting of tuples
# Each tuple should be
# (euc_distance(unknown, data_point), species)
# for each data_point in iris_data
distances = []*len(iris_data)
'''
== [(4.4866468548349108, 'setosa'),
 (4.5276925690687078, 'setosa'),
 (4.6743983570080969, 'setosa'),
 ...
 (0.44721359549995821, 'virginica'),
 (0.72801098892805138, 'virginica')]

'''
dist = iris_data[:,0:4]
distances = [euclidean_distance(unknown, i) for i in dist] 
distances = np.vstack((np.array(distances),iris_data[:,-1])).T
distances

array([[4.486646854834911, 'Iris-setosa'],
       [4.527692569068708, 'Iris-setosa'],
       [4.674398357008097, 'Iris-setosa'],
       [4.548626166217663, 'Iris-setosa'],
       [4.524378410345447, 'Iris-setosa'],
       [4.124318125460256, 'Iris-setosa'],
       [4.591296113299598, 'Iris-setosa'],
       [4.4249293779675165, 'Iris-setosa'],
       [4.709564735726646, 'Iris-setosa'],
       [4.495553358597804, 'Iris-setosa'],
       [4.355456348076513, 'Iris-setosa'],
       [4.4079473681068375, 'Iris-setosa'],
       [4.608687448721164, 'Iris-setosa'],
       [5.029910535983716, 'Iris-setosa'],
       [4.594562003064056, 'Iris-setosa'],
       [4.360045871318328, 'Iris-setosa'],
       [4.459820624195552, 'Iris-setosa'],
       [4.438468204234429, 'Iris-setosa'],
       [4.1012193308819755, 'Iris-setosa'],
       [4.393176527297759, 'Iris-setosa'],
       [4.159326868617083, 'Iris-setosa'],
       [4.331281565541543, 'Iris-setosa'],
       [4.978955713801841, 'Iris-setosa'],
       [

In [82]:
# Grab the nearest k neighbors

# Now we need to take the most frequently occuring flower
# in those k neighbors
# To do this, Make a function that takes in a list, and returns the most commonly
# occuring object. If there is a tie, return either of them

# given a list l, this code will spit back the mode
from collections import Counter
l = [1,2,3,4,3,2,2,5,8,2,2,2,5,9,2,2,5,5,3,2]
def most_frequent(l,k):
    d = Counter(l)
    return d.most_common(k)

most_frequent(l,k)

[(2, 9), (5, 4), (3, 3)]

In [87]:
# Create a list called nearest with the K nearest neighbors
nearest = most_frequent(distances[:,0],k)
nearest

[(4.495553358597804, 3), (0.9433981132056601, 2), (1.3784048752090219, 2)]

In [13]:
# use it to find the most frequent occuring flower in nearest
# note that the species is in the 1th index
most_frequent([n[1] for n in nearest])

'Iris-virginica'

In [21]:
'''
Time to put it in a function so we 
can apply the prediction
to each row in our data set!
'''    
# will default to 3 neighbors
'''
    Input:
        unknown  == four attributes of an unknown flower
        k        == the number of neighbors used
    Output:
        A prediction of the species of flower (str)
'''
def predict(unknown, k = 3):
    pass


predict([ 5.8,  2.7,  5.1,  1.9]) # == 'virginica'


'Iris-virginica'

In [23]:
'''
Putting it all together
'''

# predict each row
# Note I use row[-1] because the last element of each row 
# is the actual species
predictions = np.array([predict(row[:4]) for row in iris_data])
predictions

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [24]:
# this is the last column of the iris_data
actual = np.array([row[-1] for row in iris_data])

# accuracy of the model
np.mean(predictions == actual)

0.95999999999999996

In [25]:
# now with k == 5
predictions = np.array([predict(row[:4], k = 5) for row in iris_data])


# this is the last column of the iris_data
actual = np.array([row[-1] for row in iris_data])

# accuracy of the model
np.mean(predictions == actual)

0.96666666666666667

In [26]:
# now with k == 2
predictions = np.array([predict(row[:4], k = 2) for row in iris_data])


# this is the last column of the iris_data
actual = np.array([row[-1] for row in iris_data])

# accuracy of the model
np.mean(predictions == actual)

0.97999999999999998

In [27]:
# now with k == 1
predictions = np.array([predict(row[:4], k = 1) for row in iris_data])


# this is the last column of the iris_data
actual = np.array([row[-1] for row in iris_data])

# accuracy of the model
np.mean(predictions == actual)

WHAAATTTTTT

1.0